version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: stream_frontend
    restart: always

  backend:
    build: ./backend
    container_name: stream_backend
    env_file:
      - ./backend/.env
    volumes:
      - uploads_data:/app/uploads 
    restart: always

  worker:
    build: ./backend
    container_name: stream_worker
    command: node workers/videoWorker.js
    env_file:
      - ./backend/.env
    volumes:
      - uploads_data:/app/uploads  
    restart: always
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: stream_redis
    ports:
      - "6379:6379"
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: stream_nginx
    ports:
      - "80:80" 
    volumes:
      - uploads_data:/app/uploads  
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  uploads_data: 