server {
    listen 80;

    location / {
        proxy_pass http://stream_frontend:5173;
    }

    location /api/ {
        proxy_pass http://backend:5000/;
    }

    location /streams/ {
        alias /app/uploads/hls/;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
        add_header Cache-Control no-cache;
        expires -1;
    }
}